version: '3.8'

services:
  
  db:
    image: mysql:8.0  
    container_name: immo_db
    restart: always
    env_file:
      - .env.var
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "33066:3306"

  web:
    image: php:8.4-apache
    container_name: immo_web
    restart: always
    volumes:
      - ./immo-api-php-main:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env.var

  adminer: 
    image: adminer
    container_name: immo_adminer
    restart: always
    env_file:
      - .env.var
    ports:
      - "8081:8080" 
    depends_on:
      - db

volumes:
  db_data: